# Generated by Django 5.2.7 on 2025-10-10 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Neurodivergente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/<function get_default_profile_pic at 0x00000290C50507C0>', null=True, upload_to='profile_pics/'),
        ),
    ]
