# Generated by Django 5.2.7 on 2025-10-10 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Neurodivergente', '0007_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/<function get_default_profile_pic at 0x0000024A20BBA020>', null=True, upload_to='profile_pics/'),
        ),
    ]
